//==================================================
// This file contains the Excluded objects
// Generated By User: tobliao
// Format Version: 2
// Date: Sat Feb 14 07:09:09 2026
// ExclMode: default
//==================================================
CHECKSUM: "801845950"
INSTANCE:uvm_custom_install_recording
CHECKSUM: "4086453909"
INSTANCE:uvm_custom_install_verdi_recording
CHECKSUM: "2590293081 990500883"
INSTANCE: tb_top
Toggle 0to1 mst_ack_error "net mst_ack_error"
Toggle 1to0 mst_ack_error "net mst_ack_error"
CHECKSUM: "325075974 1784269015"
INSTANCE: tb_top.dut_slave
Fsm state "1784269015"
Transition ACK_ADDR->ADDR "2->1"
Fsm state "1784269015"
Transition DATA_TX->IDLE "5->0"
Fsm state "1784269015"
Transition DATA_RX->IDLE "3->0"
Fsm state "1784269015"
Transition ADDR->IDLE "1->0"
Fsm state "1784269015"
Transition ACK_DATA_TX->IDLE "6->0"
Fsm state "1784269015"
Transition ACK_DATA_RX->IDLE "4->0"
Fsm state "1784269015"
Transition ACK_ADDR->IDLE "2->0"
Fsm state "1784269015"
Transition IDLE->ADDR "0->1"
Fsm state "1784269015"
Transition DATA_TX->ADDR "5->1"
Fsm state "1784269015"
Transition DATA_RX->ADDR "3->1"
Fsm state "1784269015"
Transition ACK_DATA_TX->ADDR "6->1"
Fsm state "1784269015"
Transition ACK_DATA_RX->ADDR "4->1"
CHECKSUM: "2590293081 2939582255"
INSTANCE: tb_top
Condition 1 "490490816" "((slv_scl_oe && ((!slv_scl_o))) ? 1'b0 : 1'bz) 1 -1"
Condition 7 "817604307" "((mst_sda_oe && ((!mst_sda_o))) ? 1'b0 : 1'bz) 1 -1"
Condition 5 "1763958492" "((mst_scl_oe && ((!mst_scl_o))) ? 1'b0 : 1'bz) 1 -1"
Condition 3 "1151611855" "((slv_sda_oe && ((!slv_sda_o))) ? 1'b0 : 1'bz) 1 -1"
CHECKSUM: "325075974 2781547524"
INSTANCE: tb_top.dut_slave
Toggle 0to1 state [3] "logic state[3:0]"
Toggle 1to0 state [3] "logic state[3:0]"
CHECKSUM: "3211134791 3180749688"
INSTANCE: tb_top.dut_master
Toggle clk_cnt "logic clk_cnt[15:0]"
Toggle 1to0 ack_error_o "reg ack_error_o"
Toggle 0to1 ack_error_o "reg ack_error_o"
CHECKSUM: "325075974 3165181781"
INSTANCE: tb_top.dut_slave
Branch 3 "646875952" "(!rst_n)" (13) "(!rst_n) 0,MISSING_DEFAULT,-,-,-,-,-"
CHECKSUM: "3211134791 1517288048"
INSTANCE: tb_top.dut_master
Fsm state "1517288048"
Transition ACK_ADDR->IDLE "3->0"
Fsm state "1517288048"
Transition STOP->IDLE "8->0"
Fsm state "1517288048"
Transition START->IDLE "1->0"
Fsm state "1517288048"
Transition DATA_TX->IDLE "4->0"
Fsm state "1517288048"
Transition DATA_RX->IDLE "6->0"
Fsm state "1517288048"
Transition ADDR->IDLE "2->0"
Fsm state "1517288048"
Transition ACK_DATA_TX->IDLE "5->0"
Fsm state "1517288048"
Transition ACK_DATA_RX->IDLE "7->0"
CHECKSUM: "2590293081 2472660959"
INSTANCE: tb_top
Branch 0 "1061506823" "(slv_scl_oe && (!slv_scl_o))" (0) "(slv_scl_oe && (!slv_scl_o)) 1"
Branch 0 "1061506823" "(slv_scl_oe && (!slv_scl_o))" (1) "(slv_scl_oe && (!slv_scl_o)) 0"
CHECKSUM: "3211134791 4071202264"
INSTANCE: tb_top.dut_master
Branch 1 "1212022431" "(!rst_n)" (25) "(!rst_n) 0,1,MISSING_DEFAULT,-,-,-,-,-,-,-,-,-"
