//==================================================
// This file contains the Excluded objects
// Generated By User: tobliao
// Format Version: 2
// Date: Tue Jan 13 02:12:59 2026
// ExclMode: default
//==================================================
CHECKSUM: "801845950"
INSTANCE:uvm_custom_install_recording
CHECKSUM: "4086453909"
INSTANCE:uvm_custom_install_verdi_recording
CHECKSUM: "3211134791 3180749688"
INSTANCE: tb_top.dut_master
Toggle 0to1 ack_error_o "reg ack_error_o"
Toggle 1to0 ack_error_o "reg ack_error_o"
Toggle clk_cnt "logic clk_cnt[15:0]"
CHECKSUM: "3211134791 1517288048"
INSTANCE: tb_top.dut_master
Fsm state "1517288048"
Transition ACK_DATA_RX->IDLE "7->0"
Fsm state "1517288048"
Transition ACK_DATA_TX->IDLE "5->0"
Fsm state "1517288048"
Transition ADDR->IDLE "2->0"
Fsm state "1517288048"
Transition DATA_RX->IDLE "6->0"
Fsm state "1517288048"
Transition DATA_TX->IDLE "4->0"
Fsm state "1517288048"
Transition START->IDLE "1->0"
Fsm state "1517288048"
Transition STOP->IDLE "8->0"
Fsm state "1517288048"
Transition ACK_ADDR->IDLE "3->0"
CHECKSUM: "210625784 1784269015"
INSTANCE: tb_top.dut_slave
Fsm state "1784269015"
Transition ACK_DATA_RX->ADDR "4->1"
Fsm state "1784269015"
Transition ACK_DATA_TX->ADDR "6->1"
Fsm state "1784269015"
Transition DATA_RX->ADDR "3->1"
Fsm state "1784269015"
Transition DATA_TX->ADDR "5->1"
Fsm state "1784269015"
Transition IDLE->ADDR "0->1"
Fsm state "1784269015"
Transition ACK_ADDR->IDLE "2->0"
Fsm state "1784269015"
Transition ACK_DATA_RX->IDLE "4->0"
Fsm state "1784269015"
Transition ACK_DATA_TX->IDLE "6->0"
Fsm state "1784269015"
Transition ADDR->IDLE "1->0"
Fsm state "1784269015"
Transition DATA_RX->IDLE "3->0"
Fsm state "1784269015"
Transition DATA_TX->IDLE "5->0"
Fsm state "1784269015"
Transition ACK_ADDR->ADDR "2->1"
